name: .Net9 - Package and publish nuget packages

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        Write-Host "Restoring dependencies for projects:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -notmatch '\.Test\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet restore $_.FullName 
        }
    - name: Build
      run: |
        Write-Host "Building projects:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -notmatch '\.Test\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet build $_.FullName --no-restore --configuration Release
        }
    - name: Test
      run: |
        Write-Host "Running unittests:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -match '\.UnitTests\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet test $_.FullName  --verbosity normal --no-build --configuration Release
        }
    - name: publish
      run: |
        Write-Host "Publishing nuget packages:"
        Get-ChildItem -Recurse -Include *.nupkg | Where-Object { $_.FullName -like '*Release*' })) {
            Write-Host "$($_.Name)"
            dotnet nuget push $_.FullName --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }             
