name: .Net9 - Package and publish nuget packages

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore --exclude OptionA.Blazor.Maui.Test
    - name: Build
      run: dotnet build --no-restore --configuration Release --exclude OptionA.Blazor.Maui.Test
    - name: Test
      run: dotnet test --verbosity normal
    - name: publish
      run: |
        foreach($file in (Get-ChildItem -Recurse -Include *.nupkg | Where { $_.FullName -like '*Release*' })) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }             
